Support rails 5.1+
rails 5.1 dropped supporting inheriting directly from `ActiveRecord::Migration`.
Please inherit from `ActiveRecord::Migration[5.1]`.

Where `5.1` is the `major.minor` version of Rails that the migration
was originally written to support.

I think using current `major.minor` is OK because this migration is
not complicated.

```
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class ActsAsFootprintableMigration < ActiveRecord::Migration[4.2]
```